# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcomeMessage = QtWidgets.QLabel(self.centralwidget)
        self.welcomeMessage.setGeometry(QtCore.QRect(196, 0, 261, 21))
        self.welcomeMessage.setObjectName("welcomeMessage")
        self.roundsLabel = QtWidgets.QLabel(self.centralwidget)
        self.roundsLabel.setGeometry(QtCore.QRect(200, 150, 211, 20))
        self.roundsLabel.setObjectName("roundsLabel")
        self.gameImage = QtWidgets.QLabel(self.centralwidget)
        self.gameImage.setGeometry(QtCore.QRect(230, 20, 131, 121))
        self.gameImage.setText("")
        self.gameImage.setPixmap(QtGui.QPixmap("gameImage.jpg"))
        self.gameImage.setObjectName("gameImage")
        self.roundsInput = QtWidgets.QLineEdit(self.centralwidget)
        self.roundsInput.setGeometry(QtCore.QRect(250, 170, 81, 61))
        self.roundsInput.setAlignment(QtCore.Qt.AlignCenter)
        self.roundsInput.setObjectName("roundsInput")
        self.rockButton = QtWidgets.QRadioButton(self.centralwidget)
        self.rockButton.setGeometry(QtCore.QRect(160, 250, 61, 17))
        self.rockButton.setObjectName("rockButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rockButton)
        self.paperButton = QtWidgets.QRadioButton(self.centralwidget)
        self.paperButton.setGeometry(QtCore.QRect(260, 250, 61, 17))
        self.paperButton.setObjectName("paperButton")
        self.buttonGroup.addButton(self.paperButton)
        self.scissorsButton = QtWidgets.QRadioButton(self.centralwidget)
        self.scissorsButton.setGeometry(QtCore.QRect(360, 250, 82, 17))
        self.scissorsButton.setObjectName("scissorsButton")
        self.buttonGroup.addButton(self.scissorsButton)
        self.throwButton = QtWidgets.QPushButton(self.centralwidget)
        self.throwButton.setGeometry(QtCore.QRect(250, 280, 75, 23))
        self.throwButton.setObjectName("throwButton")
        self.winnerMessage = QtWidgets.QLabel(self.centralwidget)
        self.winnerMessage.setGeometry(QtCore.QRect(210, 320, 161, 20))
        self.winnerMessage.setText("")
        self.winnerMessage.setObjectName("winnerMessage")
        self.playerWins = QtWidgets.QLabel(self.centralwidget)
        self.playerWins.setGeometry(QtCore.QRect(40, 350, 151, 16))
        self.playerWins.setObjectName("playerWins")
        self.computerWins = QtWidgets.QLabel(self.centralwidget)
        self.computerWins.setGeometry(QtCore.QRect(350, 350, 151, 16))
        self.computerWins.setObjectName("computerWins")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.throwButton.clicked.connect(self.clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcomeMessage.setText(_translate("MainWindow", "Welcome to the Rock Paper Scissors game!"))
        self.roundsLabel.setText(_translate("MainWindow", "How many rounds would you like to play?"))
        self.rockButton.setText(_translate("MainWindow", "Rock"))
        self.paperButton.setText(_translate("MainWindow", "Paper"))
        self.scissorsButton.setText(_translate("MainWindow", "Scissors"))
        self.throwButton.setText(_translate("MainWindow", "Shoot!"))
        self.playerWins.setText(_translate("MainWindow", "track player wins here"))
        self.computerWins.setText(_translate("MainWindow", "track computer wins here"))



    def clicked(self):
        rounds = int(self.roundsInput.text())
        print(rounds)






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
